{{- if and .Values.persistence.tmp.enabled (not .Values.persistence.tmp.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gpubox.tmpClaimName" . }}
  labels:
    {{- include "gpubox.labels" . | nindent 4 }}
    {{- with .Values.persistence.tmp.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.tmp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.tmp.accessModes | nindent 4 }}
  volumeMode: {{ .Values.persistence.tmp.volumeMode }}
  {{- if .Values.persistence.tmp.storageClass }}
  storageClassName: {{ .Values.persistence.tmp.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.tmp.size | quote }}
{{- end }}
