apiVersion: v2
name: gpubox
description: Privileged GPU devbox StatefulSet (VS Code CLI tunnel)
type: application
version: 1.3.0
appVersion: "24.04-vscodecli-1.109.5"
keywords:
  - vscode
  - tunnel
  - gpu
  - devbox
  - privileged
